### ISSUE TITLE
Fix Compatibility with Chrome 35

### ISSUE THREAD

**Issue by bryton** [worseisbetter/galleria#335]
I am receiving the following error after upgrading to Chrome 35:

Uncaught TypeError: Failed to execute 'stroke' on 'CanvasRenderingContext2D': No function was found that matched the signature provided. 

This is using the Azur Galleria theme.

**Comment by thiagocavaloti** [comment]
I have updated Chrome to 42, and the console error is the same, like one year ago.
The galleria team have a fix to this issue?
see the error on console on this url:
http://andrecrespo.com/pintura.php?categoria=jazz

:(

**Comment by tonyellow** [comment]
I am experiencing the exact same error since one year. Can someone please have a look?

**Comment by thiagocavaloti** [comment]
@tonyellow ihave make an upgrade and the console stops to return errors :+1: );
on AZUR, i got it on VIP session.

**Comment by tonyellow** [comment]
@thiagocavaloti I can confirm that the fix works, thanks.
