### ISSUE TITLE
Gallery 1.4.2 using push functionality doesn't work if using touch devices.

### ISSUE THREAD

**Issue by ioanlucut** [worseisbetter/galleria#344]
I am using PUSH functionality of the Gallery. I am initializing the Gallery with 1 image, and then I am pushing another 10 (using push manipulation method).

The problem is that this is not working for the swipe based devices.
The following error comes:

 Uncaught TypeError: Cannot read property 'isCached' of undefined

This is because this code : self._controls.slides.push(image); happens only once in the gallery, within _run method.

**Comment by madsrode** [comment]
We get this error, did you find a solution?

**Comment by ioanlucut** [comment]
You can find a solution here : https://github.com/aino/galleria/pull/342 - however, this PR has not been until now approved. If something still doesn't work properly for you, let me know, maybe I can help.
