### ISSUE TITLE
YouTube video broken

### ISSUE THREAD

**Issue by Zeke8990** [worseisbetter/galleria#357]
YouTube recently updated their API to version 3, breaking support for gdata.youtube. Unfortunately, it seems that this project has been dead since 1.4.2 in 2014? :(

**Comment by dizlexik** [comment]
Related: http://stackoverflow.com/q/30685625/1946792
We hacked this into Galleria on our site, including the API key in the JS. Proper support would be great.

**Comment by paulsheldrake** [comment]
Galleria is currently using a deprecate Youtube API, you will need to hack the code to get it to work

**Comment by Risingson** [comment]
line 123 (getUrl):

https://www.googleapis.com/youtube/v3/videos?id=' + this.id + '&part=contentDetails&key=YOUR-GOOGLE-API-KEY

get an api key at https://console.developers.google.com/apis/credentials

**Comment by aibon** [comment]
fixed in 2a9358c18c290b639bd45e0da74c603123e3522d
