### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by cussack** [worseisbetter/galleria#360]
I don't see any activities regarding pull requests and issues in this project. @davidhellsing @sorl which way will galleria go? Do you need help?

**Comment by MarcDK** [comment]
I switched to http://photoswipe.com/ =/

**Comment by matthewmorgan** [comment]
@cussack I believe with the MIT license in place you could always fork the project and maintain your own version.  It doesn't seem to have gotten any attention in a couple of years, so if you have changes in mind that would be one way to do it.

**Comment by fiedl** [comment]
Are there any recommendable forks, yet? 
(For example, fixing the YouTube issue https://github.com/aino/galleria/issues/357?)

Cheers!

**Comment by aibon** [comment]
we're the new maintainer, aino transferred the project over to us. expect a major release version in the near future.
