### ISSUE TITLE
This project is no longer supported by Aino!

### ISSUE THREAD

**Issue by ltdesign** [worseisbetter/galleria#366]
Just a warning to anyone who comes on here... I am not an Aino spokesperson, but I have attempted to get support through the channels listed on the galleria.io website. When I looked at their support forum, I saw that the vast majority of posts are spam, and very few legitimate posts have been replied to by Aino staff. 

I would strongly suggest that if you are going to purchase a theme, to reconsider. If you ever need any support or even a refund, you will get absolutely nowhere.

**Comment by michaelthorne** [comment]
Pity, this project was a lifesaver on a few websites I built.

**Comment by MarcDK** [comment]
Is there any spiritual successor to galleria?

**Comment by aibon** [comment]
we're the new maintainer, aino transferred the project over to us. expect a major release version in the near future.
