### ISSUE TITLE
Problem with jQuery 3.1.0 load method

### ISSUE THREAD

**Issue by cspanring** [worseisbetter/galleria#373]
When using jQuery 3.1.0, jQuery's [load](http://api.jquery.com/load/) method is throwing the following error:

```TypeError: url.indexOf is not a function```

The method is called by https://github.com/worseisbetter/galleria/blob/master/src/galleria.js#L6332.

When I revert back to jQuery 2.2.4, the error disappears.

Any advice is appreciated!

**Comment by aibon** [comment]
jQuery3 isn't fully supported yet. Either use https://jquery.com/download/#jquery-migrate-plugin or stick with jQuery2.
