### ISSUE TITLE
Invalid State Error when binding elements to the tooltip

### ISSUE THREAD

**Issue by michalzubkowicz** [worseisbetter/galleria#386]
Line Utils.insertStyleTag

Produces error when inserting galleria-tooltip:
InvalidStateError

It's near the line 
` bind: function( elem, value ) {

                    // todo: revise if alternative tooltip is needed for mobile devices
                    if (Galleria.TOUCH) {
                        return;
                    }`

Happened on browsers:
Android 4.4, Android 5, Android 6, Android 7.1, Firefox 19, Firefox 20, Firefox 22, Firefox 31, Firefox 37, Firefox 38, Firefox 39, Firefox 42, Firefox 43, Firefox 44, Firefox 45, Firefox 47, Firefox 48, Firefox 49, Firefox 50, Firefox 51, Firefox 52, Firefox Mobile 40, Firefox Mobile 45, Firefox Mobile 46, Firefox Mobile 47, Firefox Mobile 49, Firefox Mobile 50, Firefox Mobile 51, Firefox Mobile 52, IE 8, IE 9, IE Mobile 9, Iceweasel 38.2

We've got about 11000 daily this kind of errors after updating galleria.io to newest version.

**Comment by aibon** [comment]
Can't reproduce, could you please escalate this via our ticket system on galleria.io or via the contact page and possibly provide more information (perhaps a link to your version)

**Comment by michalzubkowicz** [comment]
I think it was false positive related to access to indexDB (it was on time of parsing that code)
