### ISSUE TITLE
Doc updates around loadLazyThumbs / lazyLoadChunks

### ISSUE THREAD

**Issue by davidjb** [worseisbetter/galleria#394]
A few issues I noticed when trying to set up lazy loading of thumbnails:

* Reference to `loadLazyThumbs` should be updated to be `lazyLoadChunks` at http://docs.galleria.io/article/105-thumbnails. The former doesn't exist; presumably it was removed/renamed.
* Formatting for `lazyLoadChunks` needs fixing @ http://docs.galleria.io/article/130-miscellaneous

**Comment by fabrice4821** [comment]
Hi,

I try to used  thumbnails: "lazy"
But the thumbnails aren't displayed.

Can you help me ?
