### ISSUE TITLE
Couple of problems with videos (one Bug, one improvement)

### ISSUE THREAD

**Issue by Gr0m** [worseisbetter/galleria#400]
**Bug**
.destroy() method does not clear _video._inst array and because of that you can not open the Galleria again after destroy (_parseData never completes second time you run() the galleria after destroy()).

Adding "_video._inst = [];" to destroy method fixes the problem.

**Improvement**
hqdefault.jpg (480x360) youtube thumbnail can be replaced with maxresdefault.jpg

Thanks for your plugin.

**Comment by fralud** [comment]
5c97c7d8cdda19ccd6a0b2adb266d522a5f92934
