### ISSUE TITLE
How to switch to use the .light version of a theme - question/documentation

### ISSUE THREAD

**Issue by silentdiverchris** [worseisbetter/galleria#419]
I've just started playing with this gallery and it's really very snazzy, I wanted to make the surround and the  .galleria-bar element at the bottom white and tinker with the control image pngs to make the controls show up, then discovered there is a playpause-neg.png image and a .light class in the css that switches to it so I imagine there's a switch somewhere that makes the gallery use the -neg images, makes the bar white etc - just what I'm after - but can't find any mention in the issues here, the docs or with general web searches. 

I've tried searching the source for 'light' but no joy there, other than lots of false positives in the lightbox code.

Any pointers appreciated, thanks.

**Comment by sammik** [comment]
Variations are described in docs, for each theme.
https://galleriajs.github.io/docs/themes/twelve.html

How to use variations is describd in docs - options.
https://galleriajs.github.io/docs/options/variation.html

**Comment by silentdiverchris** [comment]
Awww - 'variation', missed it, thanks ever so much :)
