### ISSUE TITLE
Loading a Flickr Gallery?

### ISSUE THREAD

**Issue by xjn** [worseisbetter/galleria#84]
I'm trying to load a gallery from flickr with galleria and having no luck... sets and tags in galleria seem to work fine.

so I went to API / Explore / flickr.galleries.getPhotos at this address:
http://www.flickr.com/services/api/explore/?method=flickr.galleries.getPhotos
and put in my galleryID: 72157624423412544
and I get: "Error: K.style is undefined" in a javascript error popup...

looks like something is wrong on flickr's end of things, no?  or am I maybe screwing up the GalleryID somehow?

**Comment by JackBuh** [comment]
thanks!
